### PR TITLE
Remove dependency on kreait/firebase-php

### PR DESCRIPTION
**Pull request by jeromegamez**
As discussed on discord 🤞 

I removed some PHP 7 specific stuff (e.g. return types) to enhance compatibility with lower PHP versions - if the issue remains on your environment, I would try to add a GitHub workflow so that we can test the code with different environments and combinations of PHP version, grpc (enabled/disabled) and protobuf (enabled/disabled) - perhaps this can give us a better clue.

:octocat:

### CODE REVIEW

**Comment by MGatner** [comment]
I tried the updated version and it still causes the error (yay?). I also stuck it on a fresher Ubuntu server (adding gRPC) and still got the error, both CLI and web:
Screen Shot 2020-07-15 at 1 16 01 PM

**Comment by MGatner** [comment]
@jdpedrie in case he's here.

**Comment by jeromegamez** [comment]
Just thinking out loud...

Do you have the issue with collections of any size? How many documents does the collection you're testing with have? 

On my machine, I have the `memory_limit` set to 512M, yours seems to be set to 128M - perhaps 128M is "just not enough"? 🤔

**Comment by MGatner** [comment]
Good thoughts! My CLI memory limit is `-1` and when I run it there it just churns 100% CPU for as long as I let it go, so I definitely think it is some recursion error. The collection I've been running these tests against is pretty small, I think 30 items, and `limit(1)` *should* ensure we're only fetching the first one anyways.

**Comment by MGatner** [comment]
Here's it consuming 2GB in about 8 seconds:
Screen Shot 2020-07-15 at 1 29 36 PM

**Comment by jeromegamez** [comment]
Oh, shoot! 😅 

Could you please share the outputs of the following commands for comparison?

* `php -v`
* `pecl list`
* `composer show`

**Comment by MGatner** [comment]
Sure! Server 1:
```
$ php -v
PHP 7.3.20-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jul  9 2020 16:34:09) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.20, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.9.4, Copyright (c) 2002-2020, by Derick Rethans
    with Zend OPcache v7.3.20-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

$ pecl list
Installed packages, channel pecl.php.net:
=========================================
Package  Version State
grpc     1.25.0  stable
protobuf 3.11.2  stable
xdebug   2.9.4   stable

$ composer show
brick/math                       0.8.15   Arbitrary-precision arithmetic library
firebase/php-jwt                 v5.2.0   A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
google/auth                      v1.10.0  Google Auth Library for PHP
google/cloud-core                v1.37.1  Google Cloud PHP shared dependency, providing functionality useful to all components.
google/cloud-firestore           v1.14.0  Cloud Firestore client for PHP
google/common-protos             1.2      Google API Common Protos for PHP
google/gax                       1.3.1    Google API Core for PHP
google/grpc-gcp                  0.1.5    gRPC GCP library for channel management
google/protobuf                  v3.12.2  proto library for PHP
grpc/grpc                        1.30.0   gRPC library for PHP
guzzlehttp/guzzle                6.5.5    Guzzle is a PHP HTTP client library
guzzlehttp/promises              v1.3.1   Guzzle promises library
guzzlehttp/psr7                  1.6.1    PSR-7 message implementation that also provides common utility methods
monolog/monolog                  2.1.0    Sends your logs to files, sockets, inboxes, databases and various web services
paragonie/random_compat          v9.99.99 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
psr/cache                        1.0.1    Common interface for caching libraries
psr/http-message                 1.0.1    Common interface for HTTP messages
psr/log                          1.1.3    Common interface for logging libraries
ralouphie/getallheaders          3.0.3    A polyfill for getallheaders.
ramsey/collection                1.0.1    A PHP 7.2+ library for representing and manipulating collections.
ramsey/uuid                      4.0.1    A PHP library for generating and working with universally unique identifiers (UUIDs).
rize/uri-template                0.3.2    PHP URI Template (RFC 6570) supports both expansion & extraction
symfony/polyfill-ctype           v1.18.0  Symfony polyfill for ctype functions
symfony/polyfill-intl-idn        v1.18.0  Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer v1.18.0  Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-php70           v1.18.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72           v1.18.0  Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
```

Server 2:
```
$ php -v
PHP 7.2.24-0ubuntu0.18.04.6 (cli) (built: May 26 2020 13:09:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.6, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

$ pecl list
Installed packages, channel pecl.php.net:
=========================================
Package Version State
grpc    1.30.0  stable

$ composer show
brick/math                       0.8.15   Arbitrary-precision arithmetic library
firebase/php-jwt                 v5.2.0   A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
google/auth                      v1.10.0  Google Auth Library for PHP
google/cloud-core                v1.37.1  Google Cloud PHP shared dependency, providing functionality useful to all components.
google/cloud-firestore           v1.14.0  Cloud Firestore client for PHP
google/common-protos             1.2      Google API Common Protos for PHP
google/gax                       1.3.1    Google API Core for PHP
google/grpc-gcp                  0.1.5    gRPC GCP library for channel management
google/protobuf                  v3.12.2  proto library for PHP
grpc/grpc                        1.30.0   gRPC library for PHP
guzzlehttp/guzzle                6.5.5    Guzzle is a PHP HTTP client library
guzzlehttp/promises              v1.3.1   Guzzle promises library
guzzlehttp/psr7                  1.6.1    PSR-7 message implementation that also provides common utility methods
monolog/monolog                  2.1.0    Sends your logs to files, sockets, inboxes, databases and various web services
paragonie/random_compat          v9.99.99 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
psr/cache                        1.0.1    Common interface for caching libraries
psr/http-message                 1.0.1    Common interface for HTTP messages
psr/log                          1.1.3    Common interface for logging libraries
ralouphie/getallheaders          3.0.3    A polyfill for getallheaders.
ramsey/collection                1.0.1    A PHP 7.2+ library for representing and manipulating collections.
ramsey/uuid                      4.0.1    A PHP library for generating and working with universally unique identifiers (UUIDs).
rize/uri-template                0.3.2    PHP URI Template (RFC 6570) supports both expansion & extraction
symfony/polyfill-ctype           v1.18.0  Symfony polyfill for ctype functions
symfony/polyfill-intl-idn        v1.18.0  Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer v1.18.0  Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-php70           v1.18.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72           v1.18.0  Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
```

**Comment by jdpedrie** [comment]
Hi!

Does the error still occur when xdebug is disabled?

**Comment by jeromegamez** [comment]
@jdpedrie @MGatner Perfect timing, I just created #2 in order to test the script in different environments 😅 

It seems as if the `protobuf` extension is the determining factor, the presence of XDebug doesn't seem to make a difference 🤔

**Comment by MGatner** [comment]
Thanks so much @jeromegamez! As always your support is above-and-beyond. Google should hire you :P

@jdpedrie Hire Jerome! And also, here's the running Action:

https://github.com/MGatner/firebase-bug/actions/runs/170422528

**Comment by MGatner** [comment]
In case it matters, `xdebug` from `php -I` (should be all defaults):

```
Directive => Local Value => Master Value
xdebug.auto_trace => Off => Off
xdebug.cli_color => 0 => 0
xdebug.collect_assignments => Off => Off
xdebug.collect_includes => On => On
xdebug.collect_params => 0 => 0
xdebug.collect_return => Off => Off
xdebug.collect_vars => Off => Off
xdebug.coverage_enable => On => On
xdebug.default_enable => On => On
xdebug.dump.COOKIE => no value => no value
xdebug.dump.ENV => no value => no value
xdebug.dump.FILES => no value => no value
xdebug.dump.GET => no value => no value
xdebug.dump.POST => no value => no value
xdebug.dump.REQUEST => no value => no value
xdebug.dump.SERVER => no value => no value
xdebug.dump.SESSION => no value => no value
xdebug.dump_globals => On => On
xdebug.dump_once => On => On
xdebug.dump_undefined => Off => Off
xdebug.file_link_format => no value => no value
xdebug.filename_format => no value => no value
xdebug.force_display_errors => Off => Off
xdebug.force_error_reporting => 0 => 0
xdebug.gc_stats_enable => Off => Off
xdebug.gc_stats_output_dir => /tmp => /tmp
xdebug.gc_stats_output_name => gcstats.%p => gcstats.%p
xdebug.halt_level => 0 => 0
xdebug.idekey => no value => no value
xdebug.max_nesting_level => 256 => 256
xdebug.max_stack_frames => -1 => -1
xdebug.overload_var_dump => 2 => 2
xdebug.profiler_append => Off => Off
xdebug.profiler_enable => Off => Off
xdebug.profiler_enable_trigger => Off => Off
xdebug.profiler_enable_trigger_value => no value => no value
xdebug.profiler_output_dir => /tmp => /tmp
xdebug.profiler_output_name => cachegrind.out.%p => cachegrind.out.%p
xdebug.remote_addr_header => no value => no value
xdebug.remote_autostart => Off => Off
xdebug.remote_connect_back => Off => Off
xdebug.remote_cookie_expire_time => 3600 => 3600
xdebug.remote_enable => Off => Off
xdebug.remote_host => localhost => localhost
xdebug.remote_log => no value => no value
xdebug.remote_log_level => 7 => 7
xdebug.remote_mode => req => req
xdebug.remote_port => 9000 => 9000
xdebug.remote_timeout => 200 => 200
xdebug.scream => Off => Off
xdebug.show_error_trace => Off => Off
xdebug.show_exception_trace => Off => Off
xdebug.show_local_vars => Off => Off
xdebug.show_mem_delta => Off => Off
xdebug.trace_enable_trigger => Off => Off
xdebug.trace_enable_trigger_value => no value => no value
xdebug.trace_format => 0 => 0
xdebug.trace_options => 0 => 0
xdebug.trace_output_dir => /tmp => /tmp
xdebug.trace_output_name => trace.%c => trace.%c
xdebug.var_display_max_children => 128 => 128
xdebug.var_display_max_data => 512 => 512
xdebug.var_display_max_depth => 3 => 3
```

**Comment by MGatner** [comment]
This repo's Action agrees with Jerome: environments lacking `protobuf` get a `SIGKILL` and fail.

**Comment by MGatner** [comment]
I looked back at the original issue and I was getting segmentation faults *with* the `protobuf` extension in my actual project. https://github.com/googleapis/google-cloud-php/issues/2581#issuecomment-579887114

I will try the extension again and see if I have the same behavior on this test project - probably tonight.

**Pull request merged**
